#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from project_config import detect_uproject


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a local Codex config with Unreal MCP servers.")
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--output", default=".codex/config.local.toml")
    parser.add_argument("--mcp-unreal-command", default=shutil.which("mcp-unreal") or "mcp-unreal")
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    uproject = detect_uproject(project_root)
    output_path = (project_root / args.output).resolve()

    content = f'''# Generated by scripts/mcp/render-codex-local-config.py

[mcp_servers.unreal_mcp]
command = "npx"
args = ["unreal-engine-mcp-server"]
tool_timeout_sec = 180
startup_timeout_sec = 20

[mcp_servers.unreal_mcp.env]
UE_PROJECT_PATH = "{uproject.as_posix()}"
MCP_AUTOMATION_PORT = "8091"

[mcp_servers.mcp_unreal]
command = "{args.mcp_unreal_command}"
args = []
tool_timeout_sec = 240
startup_timeout_sec = 20

[mcp_servers.mcp_unreal.env]
MCP_UNREAL_PROJECT = "{uproject.as_posix()}"
RC_API_PORT = "30010"
PLUGIN_PORT = "8090"
'''
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote local Codex config: {output_path}")
    print("Review the generated paths and timeouts before first use.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
